# PATHS
train_dataset: ./data/train
validation_dataset: ./data/validation
predict_dataset: ./data/test
additional_functions_file: ./additional_functions.py
#load_model_path: ./CheckPoint/<chekpoint_file>
output_path: ./

# OPTIMIZATION OPTIONS
loss: loss
optimizer:
  type: Adam
  learning_rate:  0.001
metrics: [BinaryAccuracy, Precision, Recall]

# TRAINING OPTIONS
batch_size: 40
epochs: 500
epoch_size: 200
shuffle_training_set: True
shuffle_validation_set: True
val_samples: 100
val_frequency: 20
execute_gpu: False
